/**
 * SDL Key Codes
 */

function SDLK_SCANCODE_MASK() {
    return (1 << 30);
}
function SDL_SCANCODE_TO_KEYCODE(X) {
    return (X | SDLK_SCANCODE_MASK());
}

var SDL_Keycode = {

    SDLK_UNKNOWN: 0,

    SDLK_RETURN: '\r'.charCodeAt(0),
    SDLK_ESCAPE: '\033'.charCodeAt(0),
    SDLK_BACKSPACE: '\b'.charCodeAt(0),
    SDLK_TAB: '\t'.charCodeAt(0),
    SDLK_SPACE: ' '.charCodeAt(0),
    SDLK_EXCLAIM: '!'.charCodeAt(0),
    SDLK_QUOTEDBL: '"'.charCodeAt(0),
    SDLK_HASH: '#'.charCodeAt(0),
    SDLK_PERCENT: '%'.charCodeAt(0),
    SDLK_DOLLAR: '$'.charCodeAt(0),
    SDLK_AMPERSAND: '&'.charCodeAt(0),
    SDLK_QUOTE: '\''.charCodeAt(0),
    SDLK_LEFTPAREN: '('.charCodeAt(0),
    SDLK_RIGHTPAREN: ')'.charCodeAt(0),
    SDLK_ASTERISK: '*'.charCodeAt(0),
    SDLK_PLUS: '+'.charCodeAt(0),
    SDLK_COMMA: ','.charCodeAt(0),
    SDLK_MINUS: '-'.charCodeAt(0),
    SDLK_PERIOD: '.'.charCodeAt(0),
    SDLK_SLASH: '/'.charCodeAt(0),
    SDLK_0: '0'.charCodeAt(0),
    SDLK_1: '1'.charCodeAt(0),
    SDLK_2: '2'.charCodeAt(0),
    SDLK_3: '3'.charCodeAt(0),
    SDLK_4: '4'.charCodeAt(0),
    SDLK_5: '5'.charCodeAt(0),
    SDLK_6: '6'.charCodeAt(0),
    SDLK_7: '7'.charCodeAt(0),
    SDLK_8: '8'.charCodeAt(0),
    SDLK_9: '9'.charCodeAt(0),
    SDLK_COLON: ':'.charCodeAt(0),
    SDLK_SEMICOLON: ';'.charCodeAt(0),
    SDLK_LESS: '<'.charCodeAt(0),
    SDLK_EQUALS: '='.charCodeAt(0),
    SDLK_GREATER: '>'.charCodeAt(0),
    SDLK_QUESTION: '?'.charCodeAt(0),
    SDLK_AT: '@'.charCodeAt(0),
    /* Skip uppercase letters */
    SDLK_LEFTBRACKET: '['.charCodeAt(0),
    SDLK_BACKSLASH: '\\'.charCodeAt(0),
    SDLK_RIGHTBRACKET: ']'.charCodeAt(0),
    SDLK_CARET: '^'.charCodeAt(0),
    SDLK_UNDERSCORE: '_'.charCodeAt(0),
    SDLK_BACKQUOTE: '`'.charCodeAt(0),
    SDLK_a: 'a'.charCodeAt(0),
    SDLK_b: 'b'.charCodeAt(0),
    SDLK_c: 'c'.charCodeAt(0),
    SDLK_d: 'd'.charCodeAt(0),
    SDLK_e: 'e'.charCodeAt(0),
    SDLK_f: 'f'.charCodeAt(0),
    SDLK_g: 'g'.charCodeAt(0),
    SDLK_h: 'h'.charCodeAt(0),
    SDLK_i: 'i'.charCodeAt(0),
    SDLK_j: 'j'.charCodeAt(0),
    SDLK_k: 'k'.charCodeAt(0),
    SDLK_l: 'l'.charCodeAt(0),
    SDLK_m: 'm'.charCodeAt(0),
    SDLK_n: 'n'.charCodeAt(0),
    SDLK_o: 'o'.charCodeAt(0),
    SDLK_p: 'p'.charCodeAt(0),
    SDLK_q: 'q'.charCodeAt(0),
    SDLK_r: 'r'.charCodeAt(0),
    SDLK_s: 's'.charCodeAt(0),
    SDLK_t: 't'.charCodeAt(0),
    SDLK_u: 'u'.charCodeAt(0),
    SDLK_v: 'v'.charCodeAt(0),
    SDLK_w: 'w'.charCodeAt(0),
    SDLK_x: 'x'.charCodeAt(0),
    SDLK_y: 'y'.charCodeAt(0),
    SDLK_z: 'z'.charCodeAt(0),

    SDLK_CAPSLOCK: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_CAPSLOCK),

    SDLK_F1: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F1),
    SDLK_F2: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F2),
    SDLK_F3: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F3),
    SDLK_F4: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F4),
    SDLK_F5: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F5),
    SDLK_F6: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F6),
    SDLK_F7: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F7),
    SDLK_F8: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F8),
    SDLK_F9: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F9),
    SDLK_F10: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F10),
    SDLK_F11: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F11),
    SDLK_F12: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F12),

    SDLK_PRINTSCREEN: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_PRINTSCREEN),
    SDLK_SCROLLLOCK: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_SCROLLLOCK),
    SDLK_PAUSE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_PAUSE),
    SDLK_INSERT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_INSERT),
    SDLK_HOME: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_HOME),
    SDLK_PAGEUP: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_PAGEUP),
    SDLK_DELETE: '\177'.charCodeAt(0),
    SDLK_END: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_END),
    SDLK_PAGEDOWN: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_PAGEDOWN),
    SDLK_RIGHT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_RIGHT),
    SDLK_LEFT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_LEFT),
    SDLK_DOWN: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_DOWN),
    SDLK_UP: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_UP),

    SDLK_NUMLOCKCLEAR: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_NUMLOCKCLEAR),
    SDLK_KP_DIVIDE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_DIVIDE),
    SDLK_KP_MULTIPLY: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_MULTIPLY),
    SDLK_KP_MINUS: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_MINUS),
    SDLK_KP_PLUS: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_PLUS),
    SDLK_KP_ENTER: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_ENTER),
    SDLK_KP_1: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_1),
    SDLK_KP_2: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_2),
    SDLK_KP_3: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_3),
    SDLK_KP_4: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_4),
    SDLK_KP_5: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_5),
    SDLK_KP_6: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_6),
    SDLK_KP_7: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_7),
    SDLK_KP_8: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_8),
    SDLK_KP_9: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_9),
    SDLK_KP_0: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_0),
    SDLK_KP_PERIOD: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_PERIOD),

    SDLK_APPLICATION: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_APPLICATION),
    SDLK_POWER: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_POWER),
    SDLK_KP_EQUALS: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_EQUALS),
    SDLK_F13: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F13),
    SDLK_F14: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F14),
    SDLK_F15: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F15),
    SDLK_F16: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F16),
    SDLK_F17: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F17),
    SDLK_F18: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F18),
    SDLK_F19: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F19),
    SDLK_F20: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F20),
    SDLK_F21: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F21),
    SDLK_F22: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F22),
    SDLK_F23: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F23),
    SDLK_F24: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_F24),
    SDLK_EXECUTE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_EXECUTE),
    SDLK_HELP: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_HELP),
    SDLK_MENU: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_MENU),
    SDLK_SELECT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_SELECT),
    SDLK_STOP: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_STOP),
    SDLK_AGAIN: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AGAIN),
    SDLK_UNDO: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_UNDO),
    SDLK_CUT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_CUT),
    SDLK_COPY: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_COPY),
    SDLK_PASTE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_PASTE),
    SDLK_FIND: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_FIND),
    SDLK_MUTE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_MUTE),
    SDLK_VOLUMEUP: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_VOLUMEUP),
    SDLK_VOLUMEDOWN: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_VOLUMEDOWN),
    SDLK_KP_COMMA: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_COMMA),
    SDLK_KP_EQUALSAS400: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_EQUALSAS400),

    SDLK_ALTERASE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_ALTERASE),
    SDLK_SYSREQ: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_SYSREQ),
    SDLK_CANCEL: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_CANCEL),
    SDLK_CLEAR: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_CLEAR),
    SDLK_PRIOR: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_PRIOR),
    SDLK_RETURN2: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_RETURN2),
    SDLK_SEPARATOR: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_SEPARATOR),
    SDLK_OUT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_OUT),
    SDLK_OPER: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_OPER),
    SDLK_CLEARAGAIN: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_CLEARAGAIN),
    SDLK_CRSEL: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_CRSEL),
    SDLK_EXSEL: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_EXSEL),

    SDLK_KP_00: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_00),
    SDLK_KP_000: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_000),
    SDLK_THOUSANDSSEPARATOR: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_THOUSANDSSEPARATOR),
    SDLK_DECIMALSEPARATOR: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_DECIMALSEPARATOR),
    SDLK_CURRENCYUNIT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_CURRENCYUNIT),
    SDLK_CURRENCYSUBUNIT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_CURRENCYSUBUNIT),
    SDLK_KP_LEFTPAREN: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_LEFTPAREN),
    SDLK_KP_RIGHTPAREN: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_RIGHTPAREN),
    SDLK_KP_LEFTBRACE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_LEFTBRACE),
    SDLK_KP_RIGHTBRACE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_RIGHTBRACE),
    SDLK_KP_TAB: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_TAB),
    SDLK_KP_BACKSPACE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_BACKSPACE),
    SDLK_KP_A: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_A),
    SDLK_KP_B: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_B),
    SDLK_KP_C: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_C),
    SDLK_KP_D: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_D),
    SDLK_KP_E: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_E),
    SDLK_KP_F: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_F),
    SDLK_KP_XOR: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_XOR),
    SDLK_KP_POWER: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_POWER),
    SDLK_KP_PERCENT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_PERCENT),
    SDLK_KP_LESS: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_LESS),
    SDLK_KP_GREATER: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_GREATER),
    SDLK_KP_AMPERSAND: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_AMPERSAND),
    SDLK_KP_DBLAMPERSAND: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_DBLAMPERSAND),
    SDLK_KP_VERTICALBAR: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_VERTICALBAR),
    SDLK_KP_DBLVERTICALBAR: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_DBLVERTICALBAR),
    SDLK_KP_COLON: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_COLON),
    SDLK_KP_HASH: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_HASH),
    SDLK_KP_SPACE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_SPACE),
    SDLK_KP_AT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_AT),
    SDLK_KP_EXCLAM: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_EXCLAM),
    SDLK_KP_MEMSTORE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_MEMSTORE),
    SDLK_KP_MEMRECALL: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_MEMRECALL),
    SDLK_KP_MEMCLEAR: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_MEMCLEAR),
    SDLK_KP_MEMADD: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_MEMADD),
    SDLK_KP_MEMSUBTRACT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_MEMSUBTRACT),
    SDLK_KP_MEMMULTIPLY: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_MEMMULTIPLY),
    SDLK_KP_MEMDIVIDE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_MEMDIVIDE),
    SDLK_KP_PLUSMINUS: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_PLUSMINUS),
    SDLK_KP_CLEAR: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_CLEAR),
    SDLK_KP_CLEARENTRY: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_CLEARENTRY),
    SDLK_KP_BINARY: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_BINARY),
    SDLK_KP_OCTAL: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_OCTAL),
    SDLK_KP_DECIMAL: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_DECIMAL),
    SDLK_KP_HEXADECIMAL: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KP_HEXADECIMAL),

    SDLK_LCTRL: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_LCTRL),
    SDLK_LSHIFT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_LSHIFT),
    SDLK_LALT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_LALT),
    SDLK_LGUI: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_LGUI),
    SDLK_RCTRL: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_RCTRL),
    SDLK_RSHIFT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_RSHIFT),
    SDLK_RALT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_RALT),
    SDLK_RGUI: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_RGUI),

    SDLK_MODE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_MODE),

    SDLK_AUDIONEXT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AUDIONEXT),
    SDLK_AUDIOPREV: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AUDIOPREV),
    SDLK_AUDIOSTOP: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AUDIOSTOP),
    SDLK_AUDIOPLAY: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AUDIOPLAY),
    SDLK_AUDIOMUTE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AUDIOMUTE),
    SDLK_MEDIASELECT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_MEDIASELECT),
    SDLK_WWW: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_WWW),
    SDLK_MAIL: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_MAIL),
    SDLK_CALCULATOR: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_CALCULATOR),
    SDLK_COMPUTER: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_COMPUTER),
    SDLK_AC_SEARCH: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AC_SEARCH),
    SDLK_AC_HOME: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AC_HOME),
    SDLK_AC_BACK: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AC_BACK),
    SDLK_AC_FORWARD: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AC_FORWARD),
    SDLK_AC_STOP: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AC_STOP),
    SDLK_AC_REFRESH: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AC_REFRESH),
    SDLK_AC_BOOKMARKS: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_AC_BOOKMARKS),

    SDLK_BRIGHTNESSDOWN: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_BRIGHTNESSDOWN),
    SDLK_BRIGHTNESSUP: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_BRIGHTNESSUP),
    SDLK_DISPLAYSWITCH: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_DISPLAYSWITCH),
    SDLK_KBDILLUMTOGGLE: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KBDILLUMTOGGLE),
    SDLK_KBDILLUMDOWN: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KBDILLUMDOWN),
    SDLK_KBDILLUMUP: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_KBDILLUMUP),
    SDLK_EJECT: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_EJECT),
    SDLK_SLEEP: SDL_SCANCODE_TO_KEYCODE(SDL_Scancode.SDL_SCANCODE_SLEEP)

};

var SDL_Keymod = {
     KMOD_NONE:     0x0000,
     KMOD_LSHIFT:   0x0001,
     KMOD_RSHIFT:   0x0002,
     KMOD_LCTRL:    0x0040,
     KMOD_RCTRL:    0x0080,
     KMOD_LALT:     0x0100,
     KMOD_RALT:     0x0200,
     KMOD_LGUI:     0x0400,
     KMOD_RGUI:     0x0800,
     KMOD_NUM:      0x1000,
     KMOD_CAPS:     0x2000,
     KMOD_MODE:     0x4000,
     KMOD_RESERVED: 0x8000,
};

var KMOD_CTRL   = (SDL_Keymod.KMOD_LCTRL|SDL_Keymod.KMOD_RCTRL);
var KMOD_SHIFT 	= (SDL_Keymod.KMOD_LSHIFT|SDL_Keymod.KMOD_RSHIFT);
var KMOD_ALT	= (SDL_Keymod.KMOD_LALT|SDL_Keymod.KMOD_RALT);
var KMOD_GUI 	= (SDL_Keymod.KMOD_LGUI|SDL_Keymod.KMOD_RGUI);

var DOM_Keycodes = {
    8: SDL_Keycode.SDLK_BACKSPACE, //  backspace
    9: SDL_Keycode.SDLK_TAB, //  tab
    13: SDL_Keycode.SDLK_RETURN, //  enter
    16: SDL_Keycode.SDLK_LSHIFT, //  shift
    17: SDL_Keycode.SDLK_LCTRL, //  ctrl
    18: SDL_Keycode.SDLK_LALT, //  alt
    19: SDL_Keycode.SDLK_PAUSE, //  pause/break
    20: SDL_Keycode.SDLK_CAPSLOCK, //  caps lock
    27: SDL_Keycode.SDLK_ESCAPE, //  escape
    33: SDL_Keycode.SDLK_PAGEUP, // page up
    34: SDL_Keycode.SDLK_PAGEDOWN, // page down
    35: SDL_Keycode.SDLK_END, // end
    36: SDL_Keycode.SDLK_HOME, // home
    37: SDL_Keycode.SDLK_LEFT, // left arrow
    38: SDL_Keycode.SDLK_UP, // up arrow
    39: SDL_Keycode.SDLK_RIGHT, // right arrow
    40: SDL_Keycode.SDLK_DOWN, // down arrow
    45: SDL_Keycode.SDLK_INSERT, // insert
    46: SDL_Keycode.SDLK_DELETE, // delete
    48: SDL_Keycode.SDLK_0,
    49: SDL_Keycode.SDLK_1,
    50: SDL_Keycode.SDLK_2,
    51: SDL_Keycode.SDLK_3,
    52: SDL_Keycode.SDLK_4,
    53: SDL_Keycode.SDLK_5,
    54: SDL_Keycode.SDLK_6,
    55: SDL_Keycode.SDLK_7,
    56: SDL_Keycode.SDLK_8,
    57: SDL_Keycode.SDLK_9,
    65: SDL_Keycode.SDLK_a,
    66: SDL_Keycode.SDLK_b,
    67: SDL_Keycode.SDLK_c,
    68: SDL_Keycode.SDLK_d,
    69: SDL_Keycode.SDLK_e,
    70: SDL_Keycode.SDLK_f,
    71: SDL_Keycode.SDLK_g,
    72: SDL_Keycode.SDLK_h,
    73: SDL_Keycode.SDLK_i,
    74: SDL_Keycode.SDLK_j,
    75: SDL_Keycode.SDLK_k,
    76: SDL_Keycode.SDLK_l,
    77: SDL_Keycode.SDLK_m,
    78: SDL_Keycode.SDLK_n,
    79: SDL_Keycode.SDLK_o,
    80: SDL_Keycode.SDLK_p,
    81: SDL_Keycode.SDLK_q,
    82: SDL_Keycode.SDLK_r,
    83: SDL_Keycode.SDLK_s,
    84: SDL_Keycode.SDLK_t,
    85: SDL_Keycode.SDLK_u,
    86: SDL_Keycode.SDLK_v,
    87: SDL_Keycode.SDLK_w,
    88: SDL_Keycode.SDLK_x,
    89: SDL_Keycode.SDLK_y,
    90: SDL_Keycode.SDLK_z,
    //91: ?, // left window,
    //92: ?, // right window
    93: SDL_Keycode.SDLK_SELECT, // select key
    96: SDL_Keycode.SDLK_KP_0, // numpad 0
    97: SDL_Keycode.SDLK_KP_1, // numpad 1
    98: SDL_Keycode.SDLK_KP_2, // numpad 2
    99: SDL_Keycode.SDLK_KP_3, // numpad 3
    100: SDL_Keycode.SDLK_KP_4, // numpad 4
    101: SDL_Keycode.SDLK_KP_5, // numpad 5
    102: SDL_Keycode.SDLK_KP_6, // numpad 6
    103: SDL_Keycode.SDLK_KP_7, // numpad 7
    104: SDL_Keycode.SDLK_KP_8, // numpad 8
    105: SDL_Keycode.SDLK_KP_9, // numpad 9
    106: SDL_Keycode.SDLK_KP_MULTIPLY, // multiply
    107: SDL_Keycode.SDLK_KP_DIVIDE, // add
    109: SDL_Keycode.SDLK_KP_MINUS, // subtract
    110: SDL_Keycode.SDLK_KP_PERIOD, // decimal point
    111: SDL_Keycode.SDLK_KP_DIVIDE, // divide
    112: SDL_Keycode.SDLK_F1, // F1
    113: SDL_Keycode.SDLK_F2, // F2
    114: SDL_Keycode.SDLK_F3, // F3
    115: SDL_Keycode.SDLK_F4, // F4
    116: SDL_Keycode.SDLK_F5, // F5
    117: SDL_Keycode.SDLK_F6, // F6
    118: SDL_Keycode.SDLK_F7, // F7
    119: SDL_Keycode.SDLK_F8, // F8
    120: SDL_Keycode.SDLK_F9, // F9
    121: SDL_Keycode.SDLK_F10, // F10
    122: SDL_Keycode.SDLK_F11, // F11
    123: SDL_Keycode.SDLK_F12, // F12
    124: SDL_Keycode.SDLK_F13, // F13
    125: SDL_Keycode.SDLK_F14, // F14
    126: SDL_Keycode.SDLK_F15, // F15
    127: SDL_Keycode.SDLK_F16, // F16
    128: SDL_Keycode.SDLK_F17, // F17
    129: SDL_Keycode.SDLK_F18, // F18
    130: SDL_Keycode.SDLK_F19, // F19
    131: SDL_Keycode.SDLK_F20, // F20
    132: SDL_Keycode.SDLK_F21, // F21
    133: SDL_Keycode.SDLK_F22, // F22
    134: SDL_Keycode.SDLK_F23, // F23
    135: SDL_Keycode.SDLK_F24, // F24
    144: SDL_Keycode.SDLK_NUMLOCKCLEAR, // num lock
    145: SDL_Keycode.SDLK_SCROLLLOCK, // scroll lock
    160: SDL_Keycode.SDLK_CARET, // caret
    161: SDL_Keycode.SDLK_EXCLAIM, // exclaim
    162: SDL_Keycode.SDLK_QUOTEDBL, // double quote
    163: SDL_Keycode.SDLK_HASH, // hash
    164: SDL_Keycode.SDLK_DOLLAR, // dollar
    165: SDL_Keycode.SDLK_PERCENT, // percent
    166: SDL_Keycode.SDLK_AMPERSAND, // ampersand
    167: SDL_Keycode.SDLK_UNDERSCORE, // underscore
    168: SDL_Keycode.SDLK_LEFTPAREN, // open parenthesis
    169: SDL_Keycode.SDLK_RIGHTPAREN, // close parenthesis
    170: SDL_Keycode.SDLK_ASTERISK, // asterix
    171: SDL_Keycode.SDLK_PLUS, // plus
    172: SDL_Keycode.SDLK_COPY, // pipe
    173: SDL_Keycode.SDLK_MINUS, // minus
    174: SDL_Keycode.SDLK_LEFTBRACKET, // open curly bracket
    175: SDL_Keycode.SDLK_RIGHTBRACKET, // close curly bracket
    176: SDL_Keycode.SDLK_FIND, // tilde
    181: SDL_Keycode.SDLK_MUTE, // audio mute
    182: SDL_Keycode.SDLK_VOLUMEDOWN, // audio volume down
    183: SDL_Keycode.SDLK_VOLUMEUP, // audio volume up
    186: SDL_Keycode.SDLK_SEMICOLON, // semi-colon
    187: SDL_Keycode.SDLK_EQUALS, // equal-sign
    188: SDL_Keycode.SDLK_COMMA, // comma
    189: SDL_Keycode.SDLK_HASH, // dash
    190: SDL_Keycode.SDLK_PERIOD, // period
    191: SDL_Keycode.SDLK_SLASH, // forward slash
    192: SDL_Keycode.SDLK_BACKQUOTE, // grave accent
    219: SDL_Keycode.SDLK_LEFTBRACKET, // open bracket
    220: SDL_Keycode.SDLK_BACKSLASH, // back slash
    221: SDL_Keycode.SDLK_RIGHTBRACKET, // close bracket
    222: SDL_Keycode.SDLK_QUOTE, // single quote
    224: SDL_Keycode.SDLK_LGUI // meta (command/windows)
};